<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Cemaris.Application\Cemaris.Application.csproj" />
    <ProjectReference Include="..\Cemaris.Infrastructure\Cemaris.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Cemaris.Api</RootNamespace>
  </PropertyGroup>

</Project>
