// <auto-generated />
using System;
using Cemaris.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cemaris.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CemarisDbContext))]
    [Migration("20260908062036_AddManualCaseFollowUps")]
    partial class AddManualCaseFollowUps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.CaseFollowUps.CaseFollowUpAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FollowUpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FollowUpId", "CaseId");

                    b.HasIndex("FollowUpId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("CaseFollowUpAudits", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.CaseFollowUps.CaseFollowUpEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DueDate", "CreatedAtUtc", "Id");

                    b.HasIndex("CaseId", "DueDate", "CreatedAtUtc", "Id");

                    b.HasIndex("Status", "DueDate", "CreatedAtUtc", "Id");

                    b.HasIndex("CaseId", "Status", "DueDate", "CreatedAtUtc", "Id");

                    b.ToTable("CaseFollowUps", null, t =>
                        {
                            t.HasCheckConstraint("CK_CaseFollowUps_Status", "[Status] IN (N'Open', N'Completed', N'Cancelled')");

                            t.HasCheckConstraint("CK_CaseFollowUps_Title", "LEN(LTRIM(RTRIM([Title]))) > 0");

                            t.HasCheckConstraint("CK_CaseFollowUps_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.CaseFollowUps.CaseFollowUpRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FollowUpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FollowUpId", "CaseId");

                    b.HasIndex("FollowUpId", "Version")
                        .IsUnique();

                    b.ToTable("CaseFollowUpRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CaseFollowUpRevisions_OperationReason", "([Operation] = N'Created' AND [Version] = 1 AND [Reason] IS NULL) OR ([Operation] IN (N'Changed', N'Completed', N'Cancelled', N'Reopened') AND [Version] > 1 AND [Reason] IS NOT NULL AND LEN(LTRIM(RTRIM([Reason]))) > 0)");

                            t.HasCheckConstraint("CK_CaseFollowUpRevisions_Status", "[Status] IN (N'Open', N'Completed', N'Cancelled')");

                            t.HasCheckConstraint("CK_CaseFollowUpRevisions_Title", "LEN(LTRIM(RTRIM([Title]))) > 0");

                            t.HasCheckConstraint("CK_CaseFollowUpRevisions_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryAreaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CemeteryId");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "NormalizedCode")
                        .IsUnique()
                        .HasFilter("[NormalizedCode] IS NOT NULL");

                    b.HasIndex("ParentId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("CemeteryAreas", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCode")
                        .IsUnique()
                        .HasFilter("[NormalizedCode] IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Cemeteries", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryFieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AreaId");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "NormalizedCode")
                        .IsUnique()
                        .HasFilter("[NormalizedCode] IS NOT NULL");

                    b.HasIndex("ParentId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("CemeteryFields", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryGraveTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CemeteryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GraveTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GraveTypeId");

                    b.HasIndex("CemeteryId", "GraveTypeId")
                        .IsUnique();

                    b.ToTable("CemeteryGraveTypes", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryMasterDataChangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EntityKind", "EntityId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("CemeteryMasterDataChanges", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryRowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FieldId");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "NormalizedCode")
                        .IsUnique()
                        .HasFilter("[NormalizedCode] IS NOT NULL");

                    b.HasIndex("ParentId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("CemeteryRows", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.GraveSiteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlockNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("CemeteryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GraveNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("GraveTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedGraveNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("TargetCapacity")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("FieldId");

                    b.HasIndex("GraveTypeId");

                    b.HasIndex("RowId");

                    b.HasIndex("CemeteryId", "NormalizedGraveNumber")
                        .IsUnique()
                        .HasFilter("[AreaId] IS NULL AND [FieldId] IS NULL AND [RowId] IS NULL");

                    b.HasIndex("CemeteryId", "AreaId", "NormalizedGraveNumber")
                        .IsUnique()
                        .HasFilter("[AreaId] IS NOT NULL AND [FieldId] IS NULL AND [RowId] IS NULL");

                    b.HasIndex("CemeteryId", "AreaId", "FieldId", "NormalizedGraveNumber")
                        .IsUnique()
                        .HasFilter("[AreaId] IS NOT NULL AND [FieldId] IS NOT NULL AND [RowId] IS NULL");

                    b.HasIndex("CemeteryId", "AreaId", "FieldId", "RowId", "NormalizedGraveNumber")
                        .IsUnique()
                        .HasFilter("[AreaId] IS NOT NULL AND [FieldId] IS NOT NULL AND [RowId] IS NOT NULL");

                    b.ToTable("GraveSites", null, t =>
                        {
                            t.HasCheckConstraint("CK_GraveSites_OptionalHierarchy", "([AreaId] IS NOT NULL OR ([FieldId] IS NULL AND [RowId] IS NULL)) AND ([FieldId] IS NOT NULL OR [RowId] IS NULL)");

                            t.HasCheckConstraint("CK_GraveSites_Status", "[Status] IN (N'Available', N'Reserved', N'Occupied')");

                            t.HasCheckConstraint("CK_GraveSites_TargetCapacity", "[TargetCapacity] IS NULL OR [TargetCapacity] > 0");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.GraveTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BurialForm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCode")
                        .IsUnique()
                        .HasFilter("[NormalizedCode] IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("GraveTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_GraveTypes_BurialForm", "[BurialForm] IN (N'EarthBurial', N'UrnBurial', N'Mixed')");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Identity.LocalAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactPoint")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Room")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("LocalAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalAccounts_FailedLoginAttempts", "[FailedLoginAttempts] >= 0 AND [FailedLoginAttempts] <= 5");

                            t.HasCheckConstraint("CK_LocalAccounts_Role", "[Role] IN (N'Sachbearbeitung', N'Administration')");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeDraftAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NoticeDraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NoticeDraftId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("NoticeDraftAudits", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeDraftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountAssignment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AssignmentYear")
                        .HasColumnType("int");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("FeeReasonOrSource")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FinancialProductSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("NoticeDate")
                        .HasColumnType("date");

                    b.Property<string>("NoticeNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("NoticeNumberConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("NoticeNumberConfigurationVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("PayerDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PayerPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RunningNumber")
                        .HasColumnType("int");

                    b.Property<int>("RunningNumberWidthSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NoticeNumber")
                        .IsUnique();

                    b.HasIndex("NoticeNumberConfigurationId");

                    b.HasIndex("PayerPartyId");

                    b.HasIndex("CaseId", "CreatedAtUtc", "Id");

                    b.ToTable("NoticeDrafts", null, t =>
                        {
                            t.HasCheckConstraint("CK_NoticeDrafts_Amount", "[TotalAmount] > 0");

                            t.HasCheckConstraint("CK_NoticeDrafts_Currency", "[Currency] = N'EUR'");

                            t.HasCheckConstraint("CK_NoticeDrafts_NumberFacts", "[AssignmentYear] > 0 AND [RunningNumber] > 0 AND [RunningNumberWidthSnapshot] BETWEEN 1 AND 9");

                            t.HasCheckConstraint("CK_NoticeDrafts_Status", "[Status] IN (N'Draft', N'Discarded')");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeDraftRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountAssignment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AssignmentYear")
                        .HasColumnType("int");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("FeeReasonOrSource")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FinancialProductSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MutationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly>("NoticeDate")
                        .HasColumnType("date");

                    b.Property<Guid>("NoticeDraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoticeNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("NoticeNumberConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("NoticeNumberConfigurationVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayerDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PayerPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("RunningNumber")
                        .HasColumnType("int");

                    b.Property<int>("RunningNumberWidthSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NoticeDraftId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("NoticeDraftRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_NoticeDraftRevisions_Amount", "[TotalAmount] > 0");

                            t.HasCheckConstraint("CK_NoticeDraftRevisions_Currency", "[Currency] = N'EUR'");

                            t.HasCheckConstraint("CK_NoticeDraftRevisions_Status", "[Status] IN (N'Draft', N'Discarded')");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeNumberConfigurationAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("NoticeNumberConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NoticeNumberConfigurationId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("NoticeNumberConfigurationAudits", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeNumberConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FinancialProduct")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RunningNumberWidth")
                        .HasColumnType("int");

                    b.Property<byte>("SingletonKey")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SingletonKey")
                        .IsUnique();

                    b.ToTable("NoticeNumberConfigurations", null, t =>
                        {
                            t.HasCheckConstraint("CK_NoticeNumberConfigurations_Singleton", "[SingletonKey] = 1");

                            t.HasCheckConstraint("CK_NoticeNumberConfigurations_Width", "[RunningNumberWidth] BETWEEN 1 AND 9");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeNumberConfigurationRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FinancialProduct")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MutationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("NoticeNumberConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("RunningNumberWidth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoticeNumberConfigurationId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("NoticeNumberConfigurationRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_NoticeNumberConfigurationRevisions_Width", "[RunningNumberWidth] BETWEEN 1 AND 9");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeNumberSequenceEntity", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("LastIssuedNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Year");

                    b.ToTable("NoticeNumberSequences", null, t =>
                        {
                            t.HasCheckConstraint("CK_NoticeNumberSequences_Values", "[Year] > 0 AND [LastIssuedNumber] >= 0");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeGeneration.LegalBasisVersionAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LegalBasisVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LegalBasisVersionId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("LegalBasisVersionAudits", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeGeneration.LegalBasisVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("VersionDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Name", "VersionDate")
                        .IsUnique();

                    b.ToTable("LegalBasisVersions", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeGeneration.NoticeGenerationAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ExpectedNoticeDraftVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<long>("LegalBasisInternalVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LegalBasisVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NoticeDraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NoticeDraftId", "OccurredAtUtc");

                    b.ToTable("NoticeGenerationAudits", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyAddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NormalizedAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("ValidFromInclusive")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidUntilExclusive")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("PartyAddresses", null, t =>
                        {
                            t.HasCheckConstraint("CK_PartyAddresses_Period", "[ValidUntilExclusive] IS NULL OR [ValidUntilExclusive] > [ValidFromInclusive]");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentPrimaryAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id", "CurrentPrimaryAddressId");

                    b.ToTable("Parties", null, t =>
                        {
                            t.HasCheckConstraint("CK_Parties_TypeNames", "([PartyType] = N'NaturalPerson' AND [FirstName] IS NOT NULL AND [LastName] IS NOT NULL AND [OrganizationName] IS NULL) OR ([PartyType] = N'Organization' AND [FirstName] IS NULL AND [LastName] IS NULL AND [OrganizationName] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MutationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PartyId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("PartyRevisions", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.PersonUsageRightAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("PersonUsageRightAudits", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("GraveSiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StartRuleCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StartRuleDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UsageRightStartRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GraveSiteId")
                        .IsUnique();

                    b.HasIndex("UsageRightStartRuleId");

                    b.ToTable("CanonicalUsageRights", null, t =>
                        {
                            t.HasCheckConstraint("CK_CanonicalUsageRights_Dates", "[EndDate] > [StartDate]");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightHolderPeriodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsageRightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ValidFromInclusive")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidUntilExclusive")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("UsageRightId")
                        .IsUnique()
                        .HasFilter("[ValidUntilExclusive] IS NULL");

                    b.ToTable("UsageRightHolderPeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_UsageRightHolderPeriods_Period", "[ValidUntilExclusive] IS NULL OR [ValidUntilExclusive] > [ValidFromInclusive]");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MutationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsageRightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsageRightId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("UsageRightRevisions", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightStartRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CemeteryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CemeteryId")
                        .IsUnique();

                    b.ToTable("UsageRightStartRules", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightStartRuleRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MutationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UsageRightStartRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsageRightStartRuleId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("UsageRightStartRuleRevisions", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.AddressReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EntitledPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntitledPersonId");

                    b.ToTable("ReadAddresses", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.BurialReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BurialDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeceasedPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GraveSiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("PlanningDate")
                        .HasColumnType("date");

                    b.Property<string>("ProcessStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("DeceasedPersonId")
                        .IsUnique()
                        .HasFilter("[DeceasedPersonId] IS NOT NULL AND [ProcessStatus] IS NOT NULL");

                    b.HasIndex("GraveSiteId");

                    b.ToTable("ReadBurials", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReadBurials_ProcessStatus", "[ProcessStatus] IS NULL OR [ProcessStatus] IN (N'Draft', N'Planned', N'Confirmed', N'Performed', N'Completed')");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.CaseChangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("CaseChanges", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastChangedByActorId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastChangedByActorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ReadCases", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DataQualityNoteReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadDataQualityNotes", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadDeceasedPersons", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadEntitledPersons", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.FeeItemReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("NoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId");

                    b.ToTable("ReadFeeItems", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.GraveReadEntity", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cemetery")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GraveNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("GraveSiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CaseId");

                    b.HasIndex("GraveSiteId");

                    b.ToTable("ReadGraves", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AssessedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NoticeDate")
                        .HasColumnType("date");

                    b.Property<string>("NoticeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadNotices", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightHolderReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntitledPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsageRightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntitledPersonId");

                    b.HasIndex("UsageRightId", "EntitledPersonId")
                        .IsUnique();

                    b.ToTable("ReadUsageRightHolders", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadUsageRights", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.CaseFollowUps.CaseFollowUpAuditEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.CaseFollowUps.CaseFollowUpEntity", null)
                        .WithMany()
                        .HasForeignKey("FollowUpId", "CaseId")
                        .HasPrincipalKey("Id", "CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.CaseFollowUps.CaseFollowUpEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.CaseFollowUps.CaseFollowUpRevisionEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.CaseFollowUps.CaseFollowUpEntity", null)
                        .WithMany("Revisions")
                        .HasForeignKey("FollowUpId", "CaseId")
                        .HasPrincipalKey("Id", "CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryAreaEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryFieldEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryGraveTypeEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryEntity", null)
                        .WithMany()
                        .HasForeignKey("CemeteryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.GraveTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("GraveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryRowEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryFieldEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.GraveSiteEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryAreaEntity", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryEntity", "Cemetery")
                        .WithMany()
                        .HasForeignKey("CemeteryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryFieldEntity", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.GraveTypeEntity", "GraveType")
                        .WithMany()
                        .HasForeignKey("GraveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryRowEntity", "Row")
                        .WithMany()
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Area");

                    b.Navigation("Cemetery");

                    b.Navigation("Field");

                    b.Navigation("GraveType");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeDraftAuditEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeDraftEntity", null)
                        .WithMany()
                        .HasForeignKey("NoticeDraftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeDraftEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeNumberConfigurationEntity", null)
                        .WithMany()
                        .HasForeignKey("NoticeNumberConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyEntity", null)
                        .WithMany()
                        .HasForeignKey("PayerPartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeDraftRevisionEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeDraftEntity", null)
                        .WithMany("Revisions")
                        .HasForeignKey("NoticeDraftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeNumberConfigurationAuditEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeNumberConfigurationEntity", null)
                        .WithMany()
                        .HasForeignKey("NoticeNumberConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeNumberConfigurationRevisionEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeNumberConfigurationEntity", null)
                        .WithMany("Revisions")
                        .HasForeignKey("NoticeNumberConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyAddressEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyEntity", "Party")
                        .WithMany("Addresses")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyAddressEntity", null)
                        .WithMany()
                        .HasForeignKey("Id", "CurrentPrimaryAddressId")
                        .HasPrincipalKey("PartyId", "Id")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyRevisionEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyEntity", null)
                        .WithMany("Revisions")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.GraveSiteEntity", null)
                        .WithMany()
                        .HasForeignKey("GraveSiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightStartRuleEntity", null)
                        .WithMany()
                        .HasForeignKey("UsageRightStartRuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightHolderPeriodEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyEntity", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightEntity", null)
                        .WithMany("HolderPeriods")
                        .HasForeignKey("UsageRightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightRevisionEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightEntity", null)
                        .WithMany("Revisions")
                        .HasForeignKey("UsageRightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightStartRuleEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryEntity", null)
                        .WithMany()
                        .HasForeignKey("CemeteryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightStartRuleRevisionEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightStartRuleEntity", null)
                        .WithMany("Revisions")
                        .HasForeignKey("UsageRightStartRuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.AddressReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", "EntitledPerson")
                        .WithMany("Addresses")
                        .HasForeignKey("EntitledPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitledPerson");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.BurialReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("Burials")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", "DeceasedPerson")
                        .WithMany("Burials")
                        .HasForeignKey("DeceasedPersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.GraveSiteEntity", "GraveSite")
                        .WithMany()
                        .HasForeignKey("GraveSiteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Case");

                    b.Navigation("DeceasedPerson");

                    b.Navigation("GraveSite");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.CaseChangeEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("Changes")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DataQualityNoteReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("DataQualityNotes")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("DeceasedPersons")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("EntitledPersons")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.FeeItemReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", "Notice")
                        .WithMany("FeeItems")
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.GraveReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithOne("Grave")
                        .HasForeignKey("Cemaris.Infrastructure.Persistence.ReadModel.GraveReadEntity", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.GraveSiteEntity", "GraveSite")
                        .WithMany()
                        .HasForeignKey("GraveSiteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Case");

                    b.Navigation("GraveSite");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("Notices")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightHolderReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", "EntitledPerson")
                        .WithMany("UsageRights")
                        .HasForeignKey("EntitledPersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", "UsageRight")
                        .WithMany("Holders")
                        .HasForeignKey("UsageRightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitledPerson");

                    b.Navigation("UsageRight");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("UsageRights")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.CaseFollowUps.CaseFollowUpEntity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeDraftEntity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.NoticeDrafts.NoticeNumberConfigurationEntity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.PartyEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightEntity", b =>
                {
                    b.Navigation("HolderPeriods");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.PersonUsageRights.UsageRightStartRuleEntity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", b =>
                {
                    b.Navigation("Burials");

                    b.Navigation("Changes");

                    b.Navigation("DataQualityNotes");

                    b.Navigation("DeceasedPersons");

                    b.Navigation("EntitledPersons");

                    b.Navigation("Grave");

                    b.Navigation("Notices");

                    b.Navigation("UsageRights");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", b =>
                {
                    b.Navigation("Burials");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("UsageRights");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", b =>
                {
                    b.Navigation("FeeItems");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", b =>
                {
                    b.Navigation("Holders");
                });
#pragma warning restore 612, 618
        }
    }
}
