// <auto-generated />
using System;
using Cemaris.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cemaris.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CemarisDbContext))]
    [Migration("20260813104713_AddCemeteryMasterData")]
    partial class AddCemeteryMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryAreaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CemeteryId");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "NormalizedCode")
                        .IsUnique()
                        .HasFilter("[NormalizedCode] IS NOT NULL");

                    b.HasIndex("ParentId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("CemeteryAreas", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCode")
                        .IsUnique()
                        .HasFilter("[NormalizedCode] IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Cemeteries", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryFieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AreaId");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "NormalizedCode")
                        .IsUnique()
                        .HasFilter("[NormalizedCode] IS NOT NULL");

                    b.HasIndex("ParentId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("CemeteryFields", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryGraveTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CemeteryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GraveTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GraveTypeId");

                    b.HasIndex("CemeteryId", "GraveTypeId")
                        .IsUnique();

                    b.ToTable("CemeteryGraveTypes", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryMasterDataChangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EntityKind", "EntityId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("CemeteryMasterDataChanges", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryRowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FieldId");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "NormalizedCode")
                        .IsUnique()
                        .HasFilter("[NormalizedCode] IS NOT NULL");

                    b.HasIndex("ParentId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("CemeteryRows", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.GraveSiteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlockNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("CemeteryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GraveNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("GraveTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedGraveNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("TargetCapacity")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("FieldId");

                    b.HasIndex("GraveTypeId");

                    b.HasIndex("RowId");

                    b.HasIndex("CemeteryId", "NormalizedGraveNumber")
                        .IsUnique()
                        .HasFilter("[AreaId] IS NULL AND [FieldId] IS NULL AND [RowId] IS NULL");

                    b.HasIndex("CemeteryId", "AreaId", "NormalizedGraveNumber")
                        .IsUnique()
                        .HasFilter("[AreaId] IS NOT NULL AND [FieldId] IS NULL AND [RowId] IS NULL");

                    b.HasIndex("CemeteryId", "AreaId", "FieldId", "NormalizedGraveNumber")
                        .IsUnique()
                        .HasFilter("[AreaId] IS NOT NULL AND [FieldId] IS NOT NULL AND [RowId] IS NULL");

                    b.HasIndex("CemeteryId", "AreaId", "FieldId", "RowId", "NormalizedGraveNumber")
                        .IsUnique()
                        .HasFilter("[AreaId] IS NOT NULL AND [FieldId] IS NOT NULL AND [RowId] IS NOT NULL");

                    b.ToTable("GraveSites", null, t =>
                        {
                            t.HasCheckConstraint("CK_GraveSites_OptionalHierarchy", "([AreaId] IS NOT NULL OR ([FieldId] IS NULL AND [RowId] IS NULL)) AND ([FieldId] IS NOT NULL OR [RowId] IS NULL)");

                            t.HasCheckConstraint("CK_GraveSites_Status", "[Status] IN (N'Available', N'Reserved', N'Occupied')");

                            t.HasCheckConstraint("CK_GraveSites_TargetCapacity", "[TargetCapacity] IS NULL OR [TargetCapacity] > 0");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.GraveTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BurialForm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCode")
                        .IsUnique()
                        .HasFilter("[NormalizedCode] IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("GraveTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_GraveTypes_BurialForm", "[BurialForm] IN (N'EarthBurial', N'UrnBurial', N'Mixed')");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Identity.LocalAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("LocalAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalAccounts_FailedLoginAttempts", "[FailedLoginAttempts] >= 0 AND [FailedLoginAttempts] <= 5");

                            t.HasCheckConstraint("CK_LocalAccounts_Role", "[Role] IN (N'Sachbearbeitung', N'Administration')");
                        });
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.AddressReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EntitledPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntitledPersonId");

                    b.ToTable("ReadAddresses", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.BurialReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BurialDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeceasedPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("DeceasedPersonId");

                    b.ToTable("ReadBurials", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.CaseChangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "ResultingVersion")
                        .IsUnique();

                    b.ToTable("CaseChanges", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastChangedByActorId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastChangedByActorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ReadCases", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DataQualityNoteReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadDataQualityNotes", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadDeceasedPersons", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadEntitledPersons", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.FeeItemReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("NoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId");

                    b.ToTable("ReadFeeItems", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.GraveReadEntity", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cemetery")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GraveNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("GraveSiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CaseId");

                    b.HasIndex("GraveSiteId");

                    b.ToTable("ReadGraves", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AssessedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NoticeDate")
                        .HasColumnType("date");

                    b.Property<string>("NoticeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadNotices", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightHolderReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntitledPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsageRightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntitledPersonId");

                    b.HasIndex("UsageRightId", "EntitledPersonId")
                        .IsUnique();

                    b.ToTable("ReadUsageRightHolders", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadUsageRights", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryAreaEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryFieldEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryGraveTypeEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryEntity", null)
                        .WithMany()
                        .HasForeignKey("CemeteryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.GraveTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("GraveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryRowEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryFieldEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.Cemeteries.GraveSiteEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryAreaEntity", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryEntity", "Cemetery")
                        .WithMany()
                        .HasForeignKey("CemeteryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryFieldEntity", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.GraveTypeEntity", "GraveType")
                        .WithMany()
                        .HasForeignKey("GraveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.CemeteryRowEntity", "Row")
                        .WithMany()
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Area");

                    b.Navigation("Cemetery");

                    b.Navigation("Field");

                    b.Navigation("GraveType");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.AddressReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", "EntitledPerson")
                        .WithMany("Addresses")
                        .HasForeignKey("EntitledPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitledPerson");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.BurialReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("Burials")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", "DeceasedPerson")
                        .WithMany("Burials")
                        .HasForeignKey("DeceasedPersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Case");

                    b.Navigation("DeceasedPerson");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.CaseChangeEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("Changes")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DataQualityNoteReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("DataQualityNotes")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("DeceasedPersons")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("EntitledPersons")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.FeeItemReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", "Notice")
                        .WithMany("FeeItems")
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.GraveReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithOne("Grave")
                        .HasForeignKey("Cemaris.Infrastructure.Persistence.ReadModel.GraveReadEntity", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.Cemeteries.GraveSiteEntity", "GraveSite")
                        .WithMany()
                        .HasForeignKey("GraveSiteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Case");

                    b.Navigation("GraveSite");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("Notices")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightHolderReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", "EntitledPerson")
                        .WithMany("UsageRights")
                        .HasForeignKey("EntitledPersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", "UsageRight")
                        .WithMany("Holders")
                        .HasForeignKey("UsageRightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitledPerson");

                    b.Navigation("UsageRight");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("UsageRights")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", b =>
                {
                    b.Navigation("Burials");

                    b.Navigation("Changes");

                    b.Navigation("DataQualityNotes");

                    b.Navigation("DeceasedPersons");

                    b.Navigation("EntitledPersons");

                    b.Navigation("Grave");

                    b.Navigation("Notices");

                    b.Navigation("UsageRights");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", b =>
                {
                    b.Navigation("Burials");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("UsageRights");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", b =>
                {
                    b.Navigation("FeeItems");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", b =>
                {
                    b.Navigation("Holders");
                });
#pragma warning restore 612, 618
        }
    }
}
