// <auto-generated />
using System;
using Cemaris.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cemaris.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CemarisDbContext))]
    partial class CemarisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.AddressReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EntitledPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntitledPersonId");

                    b.ToTable("ReadAddresses", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.BurialReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BurialDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeceasedPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("DeceasedPersonId");

                    b.ToTable("ReadBurials", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ReadCases", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DataQualityNoteReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadDataQualityNotes", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadDeceasedPersons", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadEntitledPersons", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.FeeItemReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("NoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId");

                    b.ToTable("ReadFeeItems", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.GraveReadEntity", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cemetery")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GraveNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CaseId");

                    b.ToTable("ReadGraves", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AssessedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NoticeDate")
                        .HasColumnType("date");

                    b.Property<string>("NoticeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadNotices", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightHolderReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntitledPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsageRightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntitledPersonId");

                    b.HasIndex("UsageRightId", "EntitledPersonId")
                        .IsUnique();

                    b.ToTable("ReadUsageRightHolders", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("ReadUsageRights", (string)null);
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.AddressReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", "EntitledPerson")
                        .WithMany("Addresses")
                        .HasForeignKey("EntitledPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitledPerson");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.BurialReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("Burials")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", "DeceasedPerson")
                        .WithMany("Burials")
                        .HasForeignKey("DeceasedPersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Case");

                    b.Navigation("DeceasedPerson");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DataQualityNoteReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("DataQualityNotes")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("DeceasedPersons")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("EntitledPersons")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.FeeItemReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", "Notice")
                        .WithMany("FeeItems")
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.GraveReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithOne("Grave")
                        .HasForeignKey("Cemaris.Infrastructure.Persistence.ReadModel.GraveReadEntity", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("Notices")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightHolderReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", "EntitledPerson")
                        .WithMany("UsageRights")
                        .HasForeignKey("EntitledPersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", "UsageRight")
                        .WithMany("Holders")
                        .HasForeignKey("UsageRightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitledPerson");

                    b.Navigation("UsageRight");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", b =>
                {
                    b.HasOne("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", "Case")
                        .WithMany("UsageRights")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.CaseReadEntity", b =>
                {
                    b.Navigation("Burials");

                    b.Navigation("DataQualityNotes");

                    b.Navigation("DeceasedPersons");

                    b.Navigation("EntitledPersons");

                    b.Navigation("Grave");

                    b.Navigation("Notices");

                    b.Navigation("UsageRights");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.DeceasedReadEntity", b =>
                {
                    b.Navigation("Burials");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.EntitledPersonReadEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("UsageRights");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.NoticeReadEntity", b =>
                {
                    b.Navigation("FeeItems");
                });

            modelBuilder.Entity("Cemaris.Infrastructure.Persistence.ReadModel.UsageRightReadEntity", b =>
                {
                    b.Navigation("Holders");
                });
#pragma warning restore 612, 618
        }
    }
}
